<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-23T15:46:32 CDT" name="Default suite" finished-at="2022-06-23T15:47:07 CDT" duration-ms="35080">
    <groups>
    </groups>
    <test started-at="2022-06-23T15:46:32 CDT" name="Default test" finished-at="2022-06-23T15:47:07 CDT" duration-ms="35080">
      <class name="app.tsd.TSD_Cart">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:46:32 CDT" name="beforeClass" finished-at="2022-06-23T15:46:38 CDT" duration-ms="5711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="addItemsToCart()[pri:1, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:46:38 CDT" name="addItemsToCart" description="Add items to cart" finished-at="2022-06-23T15:46:51 CDT" duration-ms="13025" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addItemsToCart -->
        <test-method signature="changeQuantityofCart()[pri:2, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:46:51 CDT" name="changeQuantityofCart" description="Change quantity in the cart and checkout" finished-at="2022-06-23T15:46:56 CDT" duration-ms="4988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeQuantityofCart -->
        <test-method signature="createNewAccount(java.lang.String,java.lang.String,java.lang.String)[pri:3, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:46:56 CDT" name="createNewAccount" description="Create new account and address" finished-at="2022-06-23T15:47:07 CDT" duration-ms="11125" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[emailtest@domain.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Demo1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Demo1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User already exist - Expected condition failed: waiting for visibility of element located by By.xpath: //div[@class='alert alert-notice'] (tried for 10 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User already exist - Expected condition failed: waiting for visibility of element located by By.xpath: //div[@class='alert alert-notice'] (tried for 10 second(s) with 500 milliseconds interval)
at org.testng.Assert.fail(Assert.java:99)
at app.tsd.TSD_Cart.createNewAccount(TSD_Cart.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewAccount -->
        <test-method signature="fillAddress(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:4, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:47:07 CDT" name="fillAddress" description="Fill address" finished-at="2022-06-23T15:47:07 CDT" depends-on-methods="app.tsd.TSD_Cart.createNewAccount" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TSD_Cart.fillAddress(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:4, instance:app.tsd.TSD_Cart@654f0d9c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TSD_Cart.fillAddress(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:4, instance:app.tsd.TSD_Cart@654f0d9c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillAddress -->
        <test-method signature="completeDelivery()[pri:5, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:47:07 CDT" name="completeDelivery" description="Complete the delivery" finished-at="2022-06-23T15:47:07 CDT" depends-on-methods="app.tsd.TSD_Cart.fillAddress" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TSD_Cart.completeDelivery()[pri:5, instance:app.tsd.TSD_Cart@654f0d9c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TSD_Cart.completeDelivery()[pri:5, instance:app.tsd.TSD_Cart@654f0d9c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- completeDelivery -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:app.tsd.TSD_Cart@654f0d9c]" started-at="2022-06-23T15:47:07 CDT" name="afterClass" finished-at="2022-06-23T15:47:07 CDT" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- app.tsd.TSD_Cart -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
